### ISSUE TITLE
Can't upload more than 4-5MB sized files. 

### ISSUE THREAD

**Issue by masudhossain** [janko-m/shrine#176] opened 2017-07-22 11:05 UTC
I don't know the exact size, but it seems there is a limit to how much I can upload to S3. Anyone know how to change the upload size limit?

**Comment by janko-m** [comment] 2017-07-22 11:29
@masudhossain That's strange, `Shrine::Storage::S3` shouldn't impose any limits to the size of input files. How did you encounter the supposed limit? For the record, I tried [reproducing](https://gist.github.com/janko-m/b735777c7788620ce32953847e4908f6) this with a 100MB file, and it was successfully uploaded. Could you reproduce this in a self-contained example?

**Comment by masudhossain** [comment] 2017-07-23 06:56
I tried uploading a large file and this is the 'error' i get http://prntscr.com/fz534l

**Comment by janko-m** [comment] 2017-07-23 09:44
> what do you mean by self-contained example?

By that I mean that you create a script or application that I can run locally. For example, in the [gist](https://gist.github.com/janko-m/b735777c7788620ce32953847e4908f6) that I linked to, you can download that Ruby file locally and run it with `ruby` on the command line. That helps gem maintainers because they have all the code available that causes the bug.

> I tried uploading a large file and this is the 'error' i get http://prntscr.com/fz534l

Where are you uploading a file? It looks like you're uploading the file to an application which is 
behind an Nginx instance, which is configured with some limit in the size of the request body. Notice that it's an Nginx error, so it has nothing to do with Shrine.

**Comment by janko-m** [comment] 2017-07-24 08:00
I'll close this, as the problem is most likely with misconfiguration of Nginx, not with Shrine.

**Closed by janko-m** 2017-07-24 08:00 UTC

**Comment by knagode** [comment] 2023-04-30 20:25
I had similar issue with Shrine + Uppy library. At the end I figured out that there was a setting with `content_length_range` which was limiting upload as it should. 

```
Shrine.plugin :presign_endpoint, presign_options: lambda { |request|  
  filename = request.params['filename']
  type     = request.params['type']
{
    content_disposition: "inline; filename=\"#{filename}\"", 
    content_type: type, 
    content_length_range: 0..(5 * 1024 * 1024) # allow to upload 5MB
  }
}
```
