### ISSUE TITLE
Shrine generates two "versions" in PaperTrail for each create/update

### ISSUE THREAD

**Issue by walterdavis** [janko-m/shrine#121] opened 2016-12-18 19:37 UTC
I'm using Rails 5 with ActiveRecord, Shrine latest, and PaperTrail latest. When I upload an image to a new Item model, I get two events tracked in PaperTrail -- create and update. Only the second of these contains the `store` Shrine data. When I subsequently upload a different image to the saved item, I get two update records in PaperTrail. The first has the `cache` information, and the second has the `store` information. 

The result of this is that when I create navigation between versions, every other version is missing its image. (That and I have twice as many versions as I want to see or know about.)

Is there any way that the `cache` create/update could be done with something like `update_columns` that doesn't trigger any callbacks?

**Comment by janko-m** [comment] 2016-12-23 02:20
I will close this so that we can move the discussion to the [Google group thread](https://groups.google.com/forum/#!topic/ruby-shrine/2G7M9UmWlzE), as it is not a bug with Shrine.

**Closed by janko-m** 2016-12-23 02:20 UTC
