### ISSUE TITLE
cached_image_data is nil

### ISSUE THREAD

**Issue by newstler** [janko-m/shrine#152] opened 2017-03-27 11:00 UTC
Hi,

I have  a  problem that after upload the `cached_image_data` is `nil`, so when I update form without touching the image, it is being destroyed:

````
= f.simple_fields_for :poster do |poster_fields|      
  - if poster_fields.object.image_data?
    .field
      = image_tag poster_fields.object.image_url(:thumb), class: "ui fluid image"

      .field
        Remove attachment:
        = poster_fields.check_box :remove_image

  = poster_fields.hidden_field :image, value: poster_fields.object.cached_image_data
  = poster_fields.input :image, as: :file
````

For example I just created the movie record and I see the poster image
````
> m.poster.image_data
=> "{\"original\":{\"id\":\"58d8e9df78c5680334c67443\",\"storage\":\"store\",\"metadata\":{\"filename\":\"318f96601d6cf4b9ac814243a5af3f0a.jpg\",\"size\":229566,\"mime_type\":\"image/jpeg\",\"width\":1012,\"height\":1500,\"cdn_url\":\"https://originstack.cdnvideo.ru/progress_engine/images/store/922bb86d9a74c4ef3bef5aee2b3565a0.jpg\"}},\"thumb\":{\"id\":\"58d8e9df78c5680334c67444\",\"storage\":\"store\",\"metadata\":{\"filename\":\"shrine20170327-12890-6oszxs.jpg\",\"size\":17928,\"mime_type\":\"image/jpeg\",\"width\":200,\"height\":296,\"cdn_url\":\"https://originstack.cdnvideo.ru/progress_engine/images/store/055d0ea3d4bcd249053c43f59bd3addf.jpg\"}}}"
> m.poster.cached_image_data
=> nil
````

And now I just changed the year of movie
````
Started PATCH "/en/content/movies/8885fdd4-55f1-46dc-8194-87667e290eaa" for ::1 at 2017-03-27 13:57:08 +0300
Processing by Content::MoviesController#update as HTML
  Parameters: {... "content_movie"=>{"poster_attributes"=>{"remove_image"=>"0", "image"=>"", "id"=>"bb02d3ff-a9f5-4e1d-85aa-fb38397ed23e"}, ...}, "commit"=>"Save", ...}
````

Now there's no image at all
````
> m.poster.image_data
=> nil
> m.poster.cached_image_data
=> nil
````

Here's my `Poster` model:
````
class Media::Poster < ApplicationRecord
  include Uploaders::PosterUploader[:image]

  belongs_to :content, class_name: "Content::Description", inverse_of: :poster, foreign_key: "poster_id"
end
````

And `PosterUploader`:
````
require "image_processing/mini_magick"

class Uploaders::PosterUploader < Shrine
  include ImageProcessing::MiniMagick

  plugin :activerecord
  plugin :determine_mime_type
  plugin :logging, logger: Rails.logger
  plugin :remove_attachment
  plugin :store_dimensions
  plugin :validation_helpers
  plugin :versions, names: [:original, :thumb]

  Attacher.validate do
    validate_max_size 100.megabytes, message: 'is too large (max is 100 MB)'
    validate_mime_type_inclusion ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
  end

  def process(io, context)
    case context[:phase]
    when :store
      thumb = resize_to_limit!(io.download, 200, 300)
      { original: io, thumb: thumb }
    end
  end
end
````

And `config/initializers/shrine.rb`:
````
require "shrine"
require "shrine/storage/file_system"

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new("public", prefix: "uploads/cache"), # temporary
  # cache: Shrine::Storage::Platformcraft.new("cache"), # temporary — doesn't work somewhy
  store: Shrine::Storage::Platformcraft.new("store"), # permanent
}

Shrine.plugin :activerecord
Shrine.plugin :cached_attachment_data # for forms
````

What am I doing wrong?

**Comment by janko-m** [comment] 2017-03-27 11:14
That is strange, because Shrine explicitly ignores empty strings, as you can see from the following self-executable example:

```rb
require "shrine"
require "shrine/storage/file_system"
require "tmpdir"
require "stringio"

Shrine.storages[:cache] = Shrine.storages[:store] = Shrine::Storage::FileSystem.new(Dir.tmpdir)

class Photo
  attr_accessor :image_data
  include Shrine[:image]
end

photo = Photo.new
photo.image = StringIO.new("file")
photo.image = ""
p photo.image #=> #<Shrine::UploadedFile:0x007fdff6ab4360 ...>
```

Could you come up with a self-contained script that reproduces the problem using the [following template](https://github.com/janko-m/shrine/blob/master/CONTRIBUTING.md#appendix-b-activerecord-template)?

**Comment by newstler** [comment] 2017-03-27 12:38
Well, I did it and in this example the `image_data` stays untouched (I'll do some tests to see why in my code it's got erased), but the `cached_image_data` is also `nil`.

**Comment by janko-m** [comment] 2017-03-27 13:17
@newstler The `cached_image_data` is actually supposed to be `nil`, it's only non-`nil` when a new cached file has just been attached. Once the form is submitted and you render the form again, even if the file is still cached (if you're using backgrounding), `cached_image_data` will be nil. Otherwise it could happen that you still have the form with cached file rendered when the background job has already finished processing, and then when the form is submitted, the processed files would be replaced back with the cached file, triggering a new background job.

If you want to retrieve the attachment after it has been attached (whether it's cached to temporary storage or uploaded to permanent storage), just use `post.image`. The `post.cached_image_data` is only useful for form purposes.

**Comment by janko-m** [comment] 2017-03-30 01:59
The only way that Shrine will de-assign and delete the current attachment is if you assign `nil` instead of `""` (or a new file). However, as we can see from your Rails logs, a `""` is indeed being sent, and unless that value is being changed before it reaches the model, Shrine should ignore it.

```
Started PATCH "/en/content/movies/8885fdd4-55f1-46dc-8194-87667e290eaa" for ::1 at 2017-03-27 13:57:08 +0300
Processing by Content::MoviesController#update as HTML
  Parameters: {... "content_movie"=>{"poster_attributes"=>{"remove_image"=>"0", "image"=>"", "id"=>"bb02d3ff-a9f5-4e1d-85aa-fb38397ed23e"}, ...}, "commit"=>"Save", ...}
```

It would probably be useful to inspect the hash right before it gets mass-assigned to the model(s). I will close this now; if you still think this is a bug in Shrine, please create a minimal application that reproduces the problem.

**Closed by janko-m** 2017-03-30 01:59 UTC

**Comment by newstler** [comment] 2017-03-30 05:21
Yep, I managed to work this somehow, but I'm not sure what I did. I don't think this is a bug of Shrine, thank you.
