### ISSUE TITLE
Shrine background job not promoting the file to "store" with delayed_job

### ISSUE THREAD

**Issue by dkumar431** [janko-m/shrine#228] opened 2017-11-29 11:56 UTC
I am using "delayed_job" for background process. Here is the code snippet from controller.

```
    request = TranslationRequest.new
    request.advent_release_id = Advent::Release.current.id 
    request.locale = 'pt'
    request.translated_file = params[:file]
    request.save
```

With this , it is successfully uploads the file to cache. Now I am promoting to permanent storage "store" via background job. Here is the snippet.

```
  class TranslationUploader < Shrine
    Attacher.promote { |data| Delayed::Job.enqueue PromoteJob.new(data) }
  end
```

```
PromoteJob = Struct.new(:data) do
    def perform
        Shrine::Attacher.promote(data) 
    end
end
```
I have also confirmed that the background job is running fine. But `Shrine::Attacher.promote(data) `never seems to be working. Nor it throws any error.

No issues with aws and shrine setup as its working for all other cases. I have also added the background processing plugin.

**Comment by dkumar431** [comment] 2017-11-29 18:13
I have more issue too, As per the documentation, for `finalize` mehod it says 

`Deletes the old file and promotes the new one. Typically this should be called after saving the model instance.
`
Lets say we are not using any background processing. The below code promotes the file to "store", But never saves the "store" url in the db.

```
request = TranslationRequest.new
    request.advent_release_id = Advent::Release.current.id 
    request.locale = 'pt'
    request.translated_file = params[:file]
    request.save
    request.translated_file_attacher.finalize
```
But if modify the sequence of save and finalize , it seems to be working fine (i.e promotes the file to store and also updates the db record with store url)

```
request.translated_file_attacher.finalize
request.save
```

I have no clue whats going on here. Things seems to be pretty complex with this gem.

**Comment by hmistry** [comment] 2017-11-30 18:23
**Backgrounding**
I'm not sure - I'll need to try it and see.

**#finalize**
What are you trying to do by using that method? If you want to delete the file in `cache`, you can use the `delete_promoted` plugin.

**No clue/complex**
I understand... there are many moving parts and because the gem is highly modular (i.e. plugins), things can be configured in many ways to achieve different functionality. Read the [Design of Shrine](http://shrinerb.com/rdoc/files/doc/design_md.html) if you haven't already.
It would greatly help us if you can identify areas in the documentation that is lacking and how you would rewrite it to better explain things or make a PR to improve the documentation where you feel it's lacking.

**Comment by janko-m** [comment] 2017-11-30 23:27
@dkumar431 Can you include your Shrine configuration and uploader, as well as the `TranslationRequest` model declaration, including any custom `after_commit` callbacks if you have them?

I'm not really able to tell where the issue is without having the whole context, so it would be helpful if you could create a self-contained script that reproduces this behaviour. You can use [this template](https://github.com/janko-m/shrine/blob/master/CONTRIBUTING.md#appendix-b-activerecord-template).

**Comment by janko-m** [comment] 2017-12-05 11:11
One more question I forgot to ask, have you loaded the corresponding ORM plugin (`:activerecord`)?

I'm closing this issue because I don't think it is a bug in Shrine. Feel free to reopen if you were able to come up with a self-contained script that reproduces the problem.

**Closed by janko-m** 2017-12-05 11:11 UTC
