### ISSUE TITLE
AWS::S3::Errors::PermanentRedirect

### ISSUE THREAD

**Issue by swilson224** [janko-m/shrine#163] opened 2017-05-19 16:01 UTC
Hey I am using Shrine Gem with Rails 5.0.3 and ruby 2.4.0

When I attempt to upload a file I get the following message in my console and the upload fails. 

"The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint" 

now after reading some AWS Docs and stackoverflow questions / issues, the solution seems to be adding s3_host_name to the config. 

When I try to do this, shrine fails saying that its an invalid attribute. 

Do you guys have a workaround for this?

**Comment by swilson224** [comment] 2017-05-19 17:42
so I sorted this out, 

I changed up my shrine.rb file to look like so 

```
require "shrine/storage/s3"

s3_options = {
    access_key_id: ENV["AWS_ACCESS_KEY_ID"],
    secret_access_key: ENV["AWS_SECRET_KEY"],
    region: ENV["AWS_REGION"],
    bucket: ENV["AWS_BUCKET"],
    endpoint: ENV["AWS_HOST"],
}

Shrine.storages = {
    cache: Shrine::Storage::S3.new(prefix: "cache", **s3_options),
    store: Shrine::Storage::S3.new(prefix: "store", **s3_options),
}

Shrine.plugin :activerecord
Shrine.plugin :direct_upload
Shrine.plugin :restore_cached_data
```

**Comment by janko-m** [comment] 2017-05-21 03:04
I will reopen this issue, as I still want to figure out what changed, and make the appropriate patch in Shrine if necessary (because the extra `:endpoint` parameter seems redundant). Could you post your `aws-sdk` gem version, and what region are you using?

**Comment by janko-m** [comment] 2017-05-21 03:56
@swilson224 Also, it would be very useful to find out what endpoint this `aws-sdk` generate by default, when you *don't* pass it the `:endpoint` option. If you can, please let me know the output of the following script for you, and what did you put in the `AWS_HOST` env variable to fix the issue.

```rb
require "aws-sdk"

resource = Aws::S3::Resource.new(
  access_key_id: "abc",
  secret_access_key: "xyz",
  region: "eu-west-1", # put the region you're using here
)

bucket = resource.bucket("my-bucket")
object = bucket.object("key")

puts object.presigned_url(:get) # you can omit the query parameters for security
puts object.public_url
```

**Comment by janko-m** [comment] 2017-05-22 05:18
I cannot reproduce it, but the issue might be caused by a combination of the following:

* Your bucket name has dots in it (in which case the `aws-sdk` switches to the path-style URL instead of having the bucket name in the hostname)
* Your bucket resides in a different region than `ca-central-1`

Since I'm not able to reproduce the issue, I will close this. If there is an actual bug, it should probably be solved inside the `aws-sdk` gem.

**Closed by janko-m** 2017-05-22 05:18 UTC

**Comment by swilson224** [comment] 2017-05-26 03:27
Sorry i was on vacation i will update this with the info you requested. I
ended up resolving this by changing the bucket region but i did still have
to use the endpoint: to get it to work

**Comment by arcreative** [comment] 2020-12-14 22:07
I had the same issue with this, it was working fine with `us-east-1`, then when going to `eu-west-1` it was giving me this error.  Working config:

```ruby
s3_aws_region = ENV.fetch('S3_REGION', 'us-east-1')
s3_options = {
  bucket: ENV['S3_BUCKET'],
  region: s3_aws_region,
  access_key_id: ENV['S3_ACCESS_KEY_ID'],
  secret_access_key: ENV['S3_ACCESS_KEY_SECRET'],
  endpoint: ENV['S3_ENDPOINT'] || "https://#{ENV['S3_BUCKET']}.s3-#{s3_aws_region}.amazonaws.com",
}
```

**Comment by jrochkind** [comment] 2020-12-14 22:17
@arcreative your example shows you passing in "endpoint" explicitly.  And shows a default in the form of `bucketname.s3-eu-west-1.amazonaws.com`

That is a deprecated format for S3 URLs, so the PermanentRedirect may simply be telling you that. Did you get any message or other information with the error, did it tell you what it was PermanentRedirecting to?

Instead try: `bucketname.s3.eu-west-1.amazonaws.com`. 

Note the dot between `s3` and `eu-west-1` instead of a dash.  The dash format is old, S3 wants you to use the new format. That is probably the nature of the issue when are supplying the `endpoint` explicitly, you are supplying an endpoint URL in an older format that is not working. 

From https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html

> Virtual hosted style and path-style requests use the S3 dot Region endpoint structure (s3.Region), for example, https://my-bucket.s3.us-west-2.amazonaws.com. However, some older Amazon S3 Regions also support S3 dash Region endpoints s3-Region, for example, https://my-bucket.s3-us-west-2.amazonaws.com. If your bucket is in one of these Regions, you might see s3-Region endpoints in your server access logs or CloudTrail logs. We recommend that you do not use this endpoint structure in your requests.

**Comment by jrochkind** [comment] 2020-12-14 22:22
Oh wait I see that was your working config... I wonder if something before was using the wrong endpoint though somehow? I don't see anything in shrine S3 that looks like it could be, it is just using the AWS SDK. Hmm. The PermanentRedirect thing does make me think it's a wrong endpoint URL format somewhere.

**Comment by arcreative** [comment] 2020-12-17 18:14
@jrochkind Thanks, will take a look at the dot, wasn't aware of that, but the posted snippet is indeed working, while not specifying the endpoint gives me the error.  Some helpful context might also be that I used `aws s3 sync` to sync the files in question, so maybe there was some region-specific metadata that was lost on the objects themselves?
