### ISSUE TITLE
File URL with Filesystem storage misses a starting /

### ISSUE THREAD

**Issue by renchap** [janko-m/shrine#8] opened 2015-11-12 20:49 UTC
Hi !

First of all thanks for this gem, it looks very promising and I really prefer your approach compared to other I used.

I am using the Filesystem storage for now, and I find is disturbing that calling `url` on a file outputs something like `uploads/image/42/content/57940ab85648f2c416bfabc0e478ebe75233690d67abbac93b86db11f8bf.jpg`

This is not a valid URL as it is relative and I need to add a `/` in front of it in all my views (or override url in all uploaders). I could specify a host, but I would find it much more consistent to have Shrine prefix it with `/`, especially with the `subfolder` parameter.

What do you think about it ?

**Comment by renchap** [comment] 2015-11-12 22:15
Mmh, I dont really understand what happened, now I correctly have a `/` in front of my urls. I will try to reproduce, it looks like a bug.

**Comment by janko-m** [comment] 2015-11-13 01:19
Thanks for reporting, I tried reproducing it, but I didn't manage:

```rb
require "shrine/storage/file_system"
storage = Shrine::Storage::FileSystem.new("public", subdirectory: "uploads")
puts storage.url("image.jpg") #=> "/uploads/image.jpg"
```

**Comment by janko-m** [comment] 2015-11-15 20:50
This is most probably not a bug, it was most probably the result of instantiating the storage with `FileSytem.new("uploads")`, so I will close this.

**Closed by janko-m** 2015-11-15 20:50 UTC
