### ISSUE TITLE
JSON::ParserError on new uploads created with 2.4.0

### ISSUE THREAD

**Issue by erikdahlstrand** [janko-m/shrine#97] opened 2016-10-17 09:00 UTC
Hi,

The JSON data looks different on records created with Shrine 2.3.1 vs 2.4.0. As you can see on record id #20 below, the JSON data seems "double escaped". This leads to ```JSON::ParserError``` exceptions for me. I'm on Rails 5, Active Record with PostgreSQL database.

*Created with Shrine 2.3.1*

```ruby
#<Chart:0x007fb258330fb0
  id: 19,
  image_data:
   "{\"original\":{\"id\":\"b7de673bcd7a4dafda1f69a11cbac38f.png\",\"storage\":\"store\",\"metadata\":{\"filename\":\"mini_magick20160812-6551-ha9lpc.png\",\"size\":15298,\"mime_type\":\"image/png\",\"width\":720,\"height\":1280}},\"pad_16_9\":{\"id\":\"484ef39227c780a09d58250a8b6f3273.png\",\"storage\":\"store\",\"metadata\":{\"filename\":\"down20160812-6551-138p9tk20160812-6551-n1njv5.png\",\"size\":69886,\"mime_type\":\"image/png\",\"width\":1280,\"height\":720}},\"thumbnail\":{\"id\":\"eb048b61ec45cbc9ace58ca7d82e5a8c.png\",\"storage\":\"store\",\"metadata\":{\"filename\":\"down20160812-6551-138p9tk20160812-6551-f3wbin.png\",\"size\":38395,\"mime_type\":\"image/png\",\"width\":256,\"height\":256}}}",
  user_id: 1>
```

*Created with Shrine 2.4.0*

```ruby
 #<Chart:0x007fb258330e70
  id: 20,
  image_data:
   "\"{\\\"original\\\":{\\\"id\\\":\\\"129636fe758690834ca8a8a52654b77f.png\\\",\\\"storage\\\":\\\"store\\\",\\\"metadata\\\":{\\\"filename\\\":\\\"mini_magick20161017-2083-18jg7s7.png\\\",\\\"size\\\":72238,\\\"mime_type\\\":\\\"image/png\\\",\\\"width\\\":676,\\\"height\\\":560}},\\\"pad_16_9\\\":{\\\"id\\\":\\\"eefa6b566f2405cd2b45431396c3ef74.png\\\",\\\"storage\\\":\\\"store\\\",\\\"metadata\\\":{\\\"filename\\\":\\\"down20161017-2083-wyx7qt20161017-2083-1ti01i3.png\\\",\\\"size\\\":148433,\\\"mime_type\\\":\\\"image/png\\\",\\\"width\\\":1280,\\\"height\\\":720}},\\\"thumbnail\\\":{\\\"id\\\":\\\"5edd725fb9a1ac85da6266f2a6f8f483.png\\\",\\\"storage\\\":\\\"store\\\",\\\"metadata\\\":{\\\"filename\\\":\\\"down20161017-2083-wyx7qt20161017-2083-15osh2g.png\\\",\\\"size\\\":33566,\\\"mime_type\\\":\\\"image/png\\\",\\\"width\\\":256,\\\"height\\\":256}}}\"",
  user_id: 1>
```

**Comment by janko-m** [comment] 2016-10-17 09:19
@erikdahlstrand That is very unfortunate 😕. However, I wasn't able to reproduce it on the demo application, could you include your Shrine-related code?

**Comment by erikdahlstrand** [comment] 2016-10-17 09:32
I'm including two uploaders on the same model. I can see now that it's just the `image_data` and not `master_image_data` that is affected.

You helped me with a solution to keep the original filename on updates a while ago. I bet it's something in `attacher_module` that needs to be changed?

https://groups.google.com/d/topic/ruby-shrine/vDDkkLgwi10/discussion

```ruby
require 'image_processing/mini_magick'

class AnnotatedUploader < Shrine
  include ImageProcessing::MiniMagick

  plugin :data_uri
  plugin :default_url_options, cache: { public: true }, store: { public: true }
  plugin :delete_promoted
  plugin :determine_mime_type
  plugin :module_include
  plugin :processing
  plugin :remove_invalid
  plugin :store_dimensions
  plugin :validation_helpers
  plugin :versions

  Attacher.validate do
    validate_mime_type_inclusion ['image/png']

    validate_max_size 1.megabyte
    validate_max_height 1280
    validate_max_width 1280
  end

  attacher_module do
    def assign(value)
      if value
        attachment = store!(value, action: :store)
        write(attachment.to_json)
      else
        super
      end
    end
  end

  def generate_location(io, context)
    if (attachment = context[:record].send(context[:name]))
      attachment[context[:version]].id
    else
      super
    end
  end

  process(:store) do |io, _context|
    downloaded = io.is_a?(Shrine::UploadedFile) ? io.download : io

    pad_16_9 = resize_and_pad(downloaded, 1280, 720,
                              background: 'transparent',
                              gravity: 'Center')

    thumbnail = resize_to_fill(downloaded, 256, 256, gravity: 'East')

    {
      original: io,
      pad_16_9: pad_16_9,
      thumbnail: thumbnail
    }
  end
end
```

**Comment by janko-m** [comment] 2016-10-17 09:44
@erikdahlstrand Yeah, I see it. In Shrine 2.3.1 the `#write` method would simply assign the value that was given to it, but in Shrine 2.4.0 this was changed, and `#write` now calls `to_json` on the value.

I will release a new version shortly with a fix for this regression (by pushing this conversion to `#_set` again), but you should actually use `#_set` instead of `#write` (since that would also handle things like ActiveRecord Postgres JSON columns).

```rb
  attacher_module do
    def assign(value)
      if value
        attachment = store!(value, action: :store)
        _set(attachment)
      else
        super
      end
    end
  end
```

Ultimately, `Attacher#write` data should handle JSON conversion, so that it's symmetrical with `Attacher#read`, but that will wait for the next major release.

**Closed** 2016-10-17 10:53 UTC

**Comment by erikdahlstrand** [comment] 2016-10-17 13:37
2.4.1 works great. Thanks @janko-m
