### ISSUE TITLE
Error "SignatureDoesNotMatch". Google Cloud Storage Bucket PUT.

### ISSUE THREAD

**Issue by johnunclesam** [janko-m/shrine#250] opened 2018-02-12 02:17 UTC
I'm loosing my mind.

I'm using Shrine (https://github.com/janko-m/shrine) with Google Cloud Storage (https://github.com/renchap/shrine-google_cloud_storage), but when I start the `PUT` call I get this:

```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.
</Message>
<StringToSign>
PUT
image/jpeg
1518399402
/mybucket.appspot.com/7d5e4aad1e3a737fb8d2c59571fdb980.jpg
</StringToSign>
</Error>
```

I followed this info (http://shrinerb.com/rdoc/classes/Shrine/Plugins/PresignEndpoint.html) for `presign_endpoint`, but still nothing:

```ruby
class FileUploader < Shrine
  plugin :presign_endpoint, presign_options: -> (request) do
    filename     = request.params["filename"]
    extension    = File.extname(filename)
    content_type = Rack::Mime.mime_type(extension)

    {
      content_type: content_type
    }
  end
end
```

**I tried with and without this** (restarting the Rails server everytime).

Where am I wrong?

I also tried with Postman with a PUT to that URL and withtout any **content-type**. But still nothing.

I read here: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1976 and here: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1695

How can I try without Rails?

Is there a REPL (or similar) to try with my credentials and with a file?

**Comment by janko-m** [comment] 2018-02-12 02:27
Closing this one in favour of https://github.com/renchap/shrine-google_cloud_storage/issues/22, as this appears to be a bug with shrine-google_cloud_storage, not Shrine itself.

**Closed by janko-m** 2018-02-12 02:27 UTC

**Comment by johnunclesam** [comment] 2018-02-12 17:17
Maybe dear @janko-m after all this (https://github.com/renchap/shrine-google_cloud_storage/issues/22) you can take a look?

**Comment by johnunclesam** [comment] 2018-02-12 17:23
I can't find "`content_type`" in this file: https://github.com/janko-m/shrine/blob/master/lib/shrine/plugins/presign_endpoint.rb. Is it normal?

**Comment by janko-m** [comment] 2018-02-12 23:18
@johnunclesam Yes. `:content_type` is a presign option that's specific to the underlying storage. S3 and GCS both support a `:content_type` option, but for example Cloudinary does not. Shrine's presign endpoint doesn't have any knowledge about which kind of presign options you're constructing, it just forwards whatever options you specified to the `Shrine::Storage#presign` call, and then the storage takes it from there.

Nothing in this issue indicates a problem with Shrine itself, especially because in https://github.com/renchap/shrine-google_cloud_storage/issues/22 you showed that you have the same issue when using `Shrine::Storage::GoogleCloudStorage#presign` directly, which doesn't use any code from this repository whatsoever.

An issue with Shrine would be `presign_endpoint` misbehaving, but there is nothing that would indicate this; moreover, you were able to reproduce the issue without using the presign enpdoint. That's why I closed the issue here, because this problem is 100% related to shrine-google_cloud_storage, so it makes more sense to triage it there.

**Comment by johnunclesam** [comment] 2018-02-12 23:58
No, @janko-m. I have the problem just with `presign_endpoint`. In fact now my workaround is to use `Shrine.storages[:cache].presign` directly.

I strongly think the problem is with `content_type` but I can't help the seach more, unfortunately I'm newbie!

**Comment by janko-m** [comment] 2018-02-13 01:10
@johnunclesam The issue is that shrine-google_cloud_storage doesn't return the corresponding `Content-Type` header in the presign object. I opened https://github.com/renchap/shrine-google_cloud_storage/pull/23 which adds the request headers required for the upload, which will then automatically be returned by the `presign_endpoint`, and then on the client side they should be added to the request headers for the upload.

> No, @janko-m. I have the problem just with presign_endpoint. In fact now my workaround is to use Shrine.storages[:cache].presign directly.

Just to re-iterate, the same problem appeared when using `Shrine::Storage::GoogleCloudStorage#presign` directly, and even when using the bare `google-cloud-storage` gem (without `shrine-google_cloud_storage`). So it indeed wasn't a problem in Shrine's `presign_endpoint`, as it only exposes the information that `Shrine::Storage#presign` returns 😉
