### ISSUE TITLE
Shrine upload with Globalize

### ISSUE THREAD

**Issue by musixite** [janko-m/shrine#253] opened 2018-02-19 23:30 UTC
Using Globalize, I have a "featured_image_data" field that's globalized.

If I'm uploading a file, it works well for the default language.
However, when uploading a translated file, it only caches the file but doesn't store it.

Is it a bug or do I miss something obvious?

## Table
```
class CreateContentCourses < ActiveRecord::Migration[5.1]
  
  def up
    create_table :content_courses do |t|
      t.belongs_to :course_category, index: true
    	t.boolean :published, default: false
      t.date :published_at, null: true
      t.date :scheduled_for, null:true
    	t.timestamps
    end
    Content::Course.create_translation_table! :title => :string, :slug => :string, :featured_image_data => :text, :subtitle => :string, :description => :string, :foreword => :text, :translation_status => :integer
  end

  def down
    Content::Course.drop_translation_table!
  	drop_table :content_courses
  end

end
```

## Model
```
class Content::Course < ActiveRecord::Base
  attr_accessor :translation_locale

  attribute :featured_image_data

  translates :title, :slug, :featured_image_data, :subtitle, :description, :foreword, :translation_status
  globalize_accessors
  
  # uploader cover
  include CourseFeaturedImageUploader::Attachment.new(:featured_image)
```

## Uploader
```
require "image_processing/mini_magick"

class CourseFeaturedImageUploader < Shrine

  plugin :remove_attachment

  include ImageProcessing::MiniMagick
  plugin :processing
  plugin :versions   # enable Shrine to handle a hash of files
  plugin :recache
  plugin :delete_raw # delete processed files after uploading
	
  Attacher.validate do
    validate_max_size 1000*1024*1024, message: I18n.t('content.courses.form.errors.too_large_image')
    validate_mime_type_inclusion %w[image/jpeg image/png image/gif], message: I18n.t('content.courses.form.errors.not_image')
  end

	process(:recache) do |io|
		{
	    original: io
		}
	end

  process(:store) do |io, context|
		original 				= io[:original].download
    large_desktop		= resize_to_limit(original,  			1600, 1200) { |cmd| cmd.auto_orient } # orient rotated images
    desktop					= resize_to_limit(large_desktop,  1200, 800)
    tablet					= resize_to_limit(desktop,  			800, 600)
    mobile 					= resize_to_limit(tablet,  				400, 300)
    portrait_mobile	= resize_to_limit(mobile,  				300, 300)

    {
    	original: io[:original],
    	xl: 	large_desktop,
    	lg: 	desktop,
    	md: 	tablet,
    	sm: 	mobile,
    	xs: 	portrait_mobile 	
    }
  end

  Attacher.promote { |data| Delayed::Job.enqueue Content::Courses::FeaturedImagePromoteJob.new(data) }
  Attacher.delete { |data| Delayed::Job.enqueue Content::Courses::FeaturedImageDeleteJob.new(data) }

end
```

## Default Language Form
```
<% Globalize.with_locale(I18n.default_locale) do %>
<%= f.hidden_field :featured_image, value: f.object.cached_featured_image_data %>
<%= f.file_field :featured_image, id: 'featured_image', class: 'form-control' %>
<% end %>
```

## Translation Form
```
<% Globalize.with_locale(@course.translation_locale || params[:translation_locale]) do %>
<%= f.hidden_field :featured_image, value: @course.cached_featured_image_data %>
<%= f.file_field :featured_image, id: 'featured_image', class: 'form-control' %>
<% end %>

**Comment by hmistry** [comment] 2018-02-20 08:27
I tried a test script to see if Shrine works with Globalize and I confirm it's working fine with it. I see the files in cache and store directories, and in the database. See test script below. 

As to your specific problem, hard to say maybe it's failing validation or ?? You can try building up, bit by bit, the test script below to reflect your application and see which item is causing. The recache process seems unnecessary since you're not changing the image unless you removed the code for privacy reasons.

### Test Script

```
require 'bundler/setup'
require 'active_record'
# require 'sequel'
require "shrine"
require "shrine/storage/file_system"
require 'byebug'
require 'globalize'

Shrine.plugin :activerecord
Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "cache"),
  store: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "store"),
}


class MyUploader < Shrine
  # plugins and uploading logic
  plugin :validation_helpers

  Attacher.validate do
    validate_max_size 10*1024
  end
end

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Migration.verbose = false


ActiveRecord::Migration.create_table(:images) do |t|
  # t.text :image_data
end

ActiveRecord::Migration.create_table :image_translations, force: true do |t|
  t.references :image
  t.text       :image_data
  t.string     :locale
end

class Image < ActiveRecord::Base
  include MyUploader::Attachment.new(:image)
  attribute :image_data
  translates :image_data
end

I18n.config.available_locales = [:en, :nl]

# your test image
file = File.new("../test/fixtures/image.jpg")

puts "English"
I18n.locale = :en
image = Image.create(image: open(file))
puts image.inspect
puts Image.all.inspect

puts "Dutch"
I18n.locale = :nl
image = Image.create(image: open(file))
puts image.inspect
puts Image.all.inspect

# byebug
puts "done"
```

### Results
```
# English
#<Image id: 1, image_data: "{\"id\":\"3331e1828919016b18956710f3270fc8.jpg\",\"stor...">
#<ActiveRecord::Relation [#<Image id: 1, image_data: "{\"id\":\"3331e1828919016b18956710f3270fc8.jpg\",\"stor...">]>
# 
# Dutch
#<Image id: 2, image_data: "{\"id\":\"dda0735a414cdcf5a92af99fc97f6005.jpg\",\"stor...">
#<ActiveRecord::Relation [#<Image id: 1, image_data: nil>, #<Image id: 2, image_data: "{\"id\":\"dda0735a414cdcf5a92af99fc97f6005.jpg\",\"stor...">]>
# 
# Image_id:1 has nil image_data because current locale is :nl
# If I change locale to :en, then
# Image_id:1 has image_data and Image_id:2 is nil
```

**Comment by musixite** [comment] 2018-02-20 15:40
I did a few more tests and it seems that the problem comes from the versions (or recache) plugin.

When I remove the plugin, it works like you mentioned.
When I add the plugin (see below), the file is cached but not stored:

```
process(:recache) do |io|
		{
	    original: io
		}
	end

  process(:store) do |io, context|
		original 				= io[:original].download
    large_desktop		= resize_to_limit(original,  			1600, 1200) { |cmd| cmd.auto_orient } # orient rotated images
    desktop					= resize_to_limit(large_desktop,  1200, 800)
    tablet					= resize_to_limit(desktop,  			800, 600)
    mobile 					= resize_to_limit(tablet,  				400, 300)
    portrait_mobile	= resize_to_limit(mobile,  				300, 300)

    {
    	original: io[:original],
    	xl: 	large_desktop,
    	lg: 	desktop,
    	md: 	tablet,
    	sm: 	mobile,
    	xs: 	portrait_mobile 	
    }
  end
```

**Comment by hmistry** [comment] 2018-02-20 19:15
I can't reproduce your error. I added those plugins one by one but I see cache and store files as expected. 

Can you try and reproduce your error using the test script? It'll make it easy for me to have that and see what's going on.

I modified above Test script as shown below:
```
class MyUploader < Shrine
  # plugins and uploading logic
  plugin :validation_helpers
  plugin :recache
  plugin :processing
  plugin :versions

  process(:recache) do |io, context|
    # perform cheap processing
    puts "recache"
    { orig: io }
  end

  process(:store) do |io, context|
    # perform more expensive processing
    puts "store"
    { original: io[:orig], small: io[:orig].download }
  end

  Attacher.validate do
    validate_max_size 10*1024
  end
end
```

**Comment by musixite** [comment] 2018-02-21 20:27
I have tested your script and it works.
If I use my code without the background job, it works as well.

If I add the 2 lines, the default language works but not the the second one (image is cached but not stored)

So the problem are those 2 lines:
```
  Attacher.promote { |data| Delayed::Job.enqueue Content::Courses::FeaturedImagePromoteJob.new(data) }
  Attacher.delete { |data| Delayed::Job.enqueue Content::Courses::FeaturedImageDeleteJob.new(data) }
```

Just as a reference here's the corresponding jobs 
```
class Content::Courses::FeaturedImagePromoteJob < Struct.new(:data)
	def perform
    Shrine::Attacher.promote(data)
  end
end

class Content::Courses::FeaturedImageDeleteJob < Struct.new(:data)
	def perform
    Shrine::Attacher.delete(data)
  end
end
```

**Comment by hmistry** [comment] 2018-02-21 20:45
I suspect it's because you're calling `Shrine::Attacher` in `#perform` method instead of calling `CourseFeaturedImageUploader::Attacher`. `Shrine`, the base class, does not have the plugins loaded as the plugins were added in the subclass `CourseFeaturedImageUploader`. See if it works.

**Comment by hmistry** [comment] 2018-02-22 01:35
Found time to try it - used Sidekiq for inline testing and I'm more familiar with it than DelayedJob. Still working for me, can't reproduce your issue. Any errors in your logs, backtraces, validation fails, ...?

### Test Script with background jobs
```
require 'bundler/setup'
require 'active_record'
# require 'sequel'
require "shrine"
require "shrine/storage/file_system"
require 'byebug'

require 'globalize'

require 'sidekiq/testing'
Sidekiq::Testing.inline!

Shrine.plugin :activerecord
# Shrine.plugin :backgrounding  # method 1: use with lines #53 & #61

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "cache"),
  store: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "store"),
}


class MyUploader < Shrine
  # plugins and uploading logic
  plugin :validation_helpers
  plugin :recache
  plugin :processing
  plugin :versions
  plugin :backgrounding  # method 2: use with lines #54 & #62

  process(:recache) do |io, context|
    # perform cheap processing
    puts "recache"
    { orig: io }
  end

  process(:store) do |io, context|
    # perform more expensive processing
    puts "store"
    { original: io[:orig], small: io[:orig].download }
  end

  Attacher.validate do
    validate_max_size 10*1024
  end

  Attacher.promote { |data| PromoteJob.perform_async(data) }
  Attacher.delete { |data| DeleteJob.perform_async(data) }
end

class PromoteJob
  include Sidekiq::Worker
  def perform(data)
    # Shrine::Attacher.promote(data)  # method 1
    MyUploader::Attacher.promote(data)  # method 2
  end
end

class DeleteJob
  include Sidekiq::Worker
  def perform(data)
    # Shrine::Attacher.delete(data)  # method 1
    MyUploader::Attacher.delete(data)  # method 2
  end
end

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Migration.verbose = false


ActiveRecord::Migration.create_table(:images) do |t|
  # t.text :image_data
end

ActiveRecord::Migration.create_table :image_translations, force: true do |t|
  t.references :image
  t.text       :image_data
  t.string     :locale
end

class Image < ActiveRecord::Base
  include MyUploader::Attachment.new(:image)
  attribute :image_data
  translates :image_data
end

I18n.config.available_locales = [:en, :nl]

# your test image
file = File.new("../test/fixtures/image.jpg")

puts "English"
I18n.locale = :en
image = Image.create(image: open(file))
puts image.inspect
puts Image.all.inspect

puts "Dutch"
I18n.locale = :nl
image = Image.create(image: open(file))
puts image.inspect
puts Image.all.inspect

# byebug
puts "done"
```

**Comment by musixite** [comment] 2018-02-22 17:56
I did some more tests and here's what I noticed: the background jobs are executed but with the second language, it doesn't perform this line:
```
    Shrine::Attacher.promote(data)
```

In other words, the job works but is empty. (there are no errors on the log)

I'm wondering if this might be the locale variable which causes the problem on my form.

Default language uses:
```
<%= form_for @course, url: content_course_url(@course.id, locale: I18n.default_locale), html: { id: 'formEditCourse', class: 'ui form', multipart: true } do |f| %>
<% Globalize.with_locale(I18n.default_locale) do %>
	<h5 class="card-title mb-3"><%= t('content.courses.form.labels.featured_image') %></h5>
	<% unless f.object.featured_image_url(:md).nil? %>
		<div class="mb-3">
		<img src="<%= f.object.featured_image_url(:original) %>" id="featured_image_crop" class="img img-fluid img-thumbnail"></img>
		</div>
	<% end %>
	<div id="preview" class="mb-3 d-none">
	<img id="featured_image_preview" class="img img-fluid img-thumbnail" />
	</div>
	<div class="form-group">
	<%= f.hidden_field :featured_image, value: f.object.cached_featured_image_data %>
	<%= f.file_field :featured_image, id: 'featured_image', class: 'form-control' %>
	<small class="form-text text-muted"><%= t('content.courses.form.info.featured_image') %></small>
	</div>
	<div class="form-check">
	<%= f.check_box :remove_featured_image, class: 'form-check-input' %>
	<label class="form-check-label"><%= t('content.courses.form.labels.remove_featured_image') %></label>
	</div>
	<% end %>
<% end %>
```

Second language uses a locale param to temporarily set the locale:
```
<%= form_for @course, url: translations_course_url(@course.id, locale: params[:translation_locale]), html: { id: 'formEditCourseTranslation' } do |f| %>
	<% Globalize.with_locale(@course.translation_locale || params[:translation_locale]) do %>
		<% unless @course.featured_image_url(:md).nil? %>
			<div class="mb-3">
			    <img src="<%= @course.featured_image_url(:original) %>" id="featured_image_crop" class="img img-fluid img-thumbnail"></img>
			  </div>
		<% end %>
		<div class="form-group">
			<%= f.hidden_field :featured_image, value: @course.cached_featured_image_data %>
			<%= f.file_field :featured_image, id: 'featured_image', class: 'form-control' %>
			<small class="form-text text-muted"><%= t('content.courses.form.info.featured_image') %></small>
		</div>
		<div class="form-check">
			<%= f.check_box :remove_featured_image, class: 'form-check-input' %>
			<label class="form-check-label"><%= t('content.courses.form.labels.remove_featured_image') %></label>
		</div>
	<% end %>
<% end %>

Each form has its own controller.

Any ideas?

**Comment by hmistry** [comment] 2018-02-22 18:13
If the job works then I'm afraid this is where I draw the line. I think this is an application issue and not an issue with Shrine. I've proven in the test scripts that Shrine works fine with globalize and different locales. 

Unless **you create a test script reproducing your error and highlighting a bug in Shrine**, I cannot help you. Don't take this the wrong way but my time is limited and I'm not able to help everyone debug their applications.

**Comment by musixite** [comment] 2018-02-22 19:30
I totally understand and I'm thankful for your help!

I'll keep investigating and get back here if I see something unusual.

Thanks again :)

**Comment by janko-m** [comment] 2018-02-22 22:15
@musixite Did you try to reproduce the issue in an isolated script like @hmistry has demonstrated? That will guarantee you that we would be able to fix the potential issue, and you'll also most likely figure out what causes it yourself (that usually happens to me when I report bugs on other projects).

Since there is no evidence that there is a bug in Shrine, I will close the issue for now.

**Closed by janko-m** 2018-02-22 22:15 UTC
