### ISSUE TITLE
Getting error ERR_CONNECTION_REFUSED on direct upload in rails

### ISSUE THREAD

**Issue by flyingboy007** [janko-m/shrine#25] opened 2015-12-12 10:28 UTC
I cloned the rails example app https://github.com/janko-m/shrine-rails-example/tree/improvements

I have done everything as per the readme but when uploading a file am getting this error on the browser console.

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading
> the remote resource at
> https://example-bucket.s3.ap-southeast.amazonaws.com/. (Reason: CORS
> request failed).

Here is my cors settings

```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>http://localhost:3000</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
</CORSConfiguration>
```

Could someone tell me whats wrong here?

**Comment by janko-m** [comment] 2015-12-12 13:07
This is a standard error when CORS isn't properly working. How long after setting up CORS did this happen? It is noted in Shrine's "Direct Uploads to S3" guide:

> Note that it may take some time for the CORS settings to be applied, due to DNS propagation.

**Comment by flyingboy007** [comment] 2015-12-12 13:32
tried after 3-4 hours still same..

**Comment by janko-m** [comment] 2015-12-12 13:51
I have almost the same CORS setup as you do, just that "GET" method is replaced with "DELETE". It tried in Chrome/Safari/Firefox. I have to admit that I was also having a problem, where a CORS setup that was working before (which wasn't the officially recommended one) suddenly stopped working, and I never really figured it out.

Aha, I think I see now what's the problem, I think you've set the region to `ap-southeast`, but the region name should be either `ap-southeast-1` or `ap-southeast-2`: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by flyingboy007** [comment] 2015-12-12 14:52
Exactly mate..didnt even think that was the issue..was deleting and reconfiguring buckets whole day....This gem is great.. I think there are some issue like images left over in cache if we select multiple files..anyway need to do look and will report it as it comes.. Thanks a lot for making this awesome gem..

**Comment by janko-m** [comment] 2015-12-12 21:29
Awesome, I'm glad you like Shrine :)

Images being left in the cache is the expected behaviour. It wasn't like this prior to 1.0, cached files were automatically deleted when they are moved to store. However, that behaviour was causing several issues:

* If `moving` plugin is used without processing, errors would be raised because the file would be deleted twice. I had a hack against that at the moment, but it was kind of ugly.
* If the record is retrieved in the controller and the page starts being rendered, and in the meanwhile the attachments gets successfully promoted, the cached file could get deleted before the browser starts downloading the image, resulting in a broken image tag (fixed by refreshing the page). This probably wouldn't happen often, but when it happens it's not nice UX.
* Automatically deleting promoted cached files could make users think that this will keep the cache clean. However, if you're using direct uploads, or even if you're not, the user (attacker) can still start filling up your cache if they wanted to. This is not a reason of course, just that in that case you would still need a [mechanism of automatically deleting your cache](https://github.com/janko-m/shrine#clearing-cache).

**Closed by janko-m** 2015-12-12 21:29 UTC
