### ISSUE TITLE
S3 upload of videos (mp4) from an uploader to 'store' storage expects content_md5 to be set in options hash with md5 at Shrine::Storage::S3#put

### ISSUE THREAD

**Issue by jaymanklu** [janko-m/shrine#58] opened 2016-04-25 07:35 UTC
Hi, I am using shrine to upload videos to S3 from a Rails app.

My mongoid model for storing video looks like this:
```ruby
class Video
  include Mongoid::Document
  include Mongoid::Timestamps
  include VideoUploader[:file]

  field :file_data, type: String
end
```

And `VideoUploader` for the same looks like this:
```ruby
class VideoUploader < Shrine
  plugin :determine_mime_type
  plugin :remove_attachment
  plugin :store_dimensions
  plugin :validation_helpers
  plugin :versions, names: [:default]
  plugin :moving, storages: [:cache]

  def process(io, context)
    case context[:phase]
    when :store
      original  = io.download

      { default: original }
    end
  end
end
```

From a Rails form I directly upload video to S3 `cache` storage using `jquery-fileupload`

And I am using a standard `Sidekiq` worker with `Shrine::Attacher.promote(data)` for moving video from `cache` to `store` storage.

When this background job runs, I get this stacktrace:

```
2016-04-22T11:31:46.853Z 22691 TID-12o5n0 WARN: Aws::S3::Errors::BadDigest: The Content-MD5 you specified did not match what we received.
2016-04-22T11:31:46.854Z 22691 TID-12o5n0 WARN: /home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/aws-sdk-core-2.1.18/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/aws-sdk-core-2.1.18/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:18:in `call'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/aws-sdk-core-2.1.18/lib/aws-sdk-core/plugins/param_converter.rb:21:in `call'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/aws-sdk-core-2.1.18/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/aws-sdk-core-2.1.18/lib/seahorse/client/request.rb:70:in `send_request'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/aws-sdk-core-2.1.18/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/aws-sdk-resources-2.1.18/lib/aws-sdk-resources/request.rb:24:in `call'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/aws-sdk-resources-2.1.18/lib/aws-sdk-resources/operations.rb:41:in `call'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/aws-sdk-resources-2.1.18/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine/storage/s3.rb:241:in `put'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine/storage/s3.rb:128:in `upload'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine.rb:337:in `copy'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine/plugins/moving.rb:45:in `copy'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine.rb:332:in `put'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine.rb:316:in `_store'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine/plugins/versions.rb:148:in `_store'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine/plugins/versions.rb:145:in `block in _store'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine/plugins/versions.rb:144:in `each'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine/plugins/versions.rb:144:in `inject'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine/plugins/versions.rb:144:in `_store'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine.rb:243:in `store'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine/plugins/logging.rb:82:in `block in store'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine/plugins/logging.rb:97:in `block in log'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine/plugins/logging.rb:155:in `block in benchmark'
/home/dev/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine/plugins/logging.rb:155:in `benchmark'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine/plugins/logging.rb:97:in `log'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine/plugins/logging.rb:82:in `store'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine.rb:214:in `upload'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine.rb:606:in `store!'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine.rb:529:in `promote'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/bundler/gems/shrine-8a0623979c6e/lib/shrine/plugins/backgrounding.rb:70:in `promote'
/home/dev/apps/staging/releases/20160422111751/app/workers/shrine/upload_job.rb:9:in `perform'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/processor.rb:75:in `execute_job'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/server/logging.rb:15:in `block in call'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/logging.rb:30:in `with_context'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/server/logging.rb:11:in `call'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/processor.rb:51:in `block in process'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/processor.rb:98:in `stats'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.1/lib/sidekiq/processor.rb:50:in `process'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/home/dev/apps/staging/shared/bundle/ruby/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

Looking through the stacktrace and reaching [Shrine::Storage::S3#put](https://github.com/janko-m/shrine/blob/master/lib/shrine/storage/s3.rb#L236), I noticed that shrine does not send `content_md5` with md5 hash of the file in options hash. And S3 does not seem to be expecting it too, but only in the case of video upload, it seems to be throwing an exception when S3 doesn't find it.

I could fix this by calculating md5 hash for the video being uploaded and add to options hash at [Shrine::Storage::S3#put](https://github.com/janko-m/shrine/blob/master/lib/shrine/storage/s3.rb#L236), by referencing aws-sdk docs for [`AWS::S3::Object#put`](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Object.html#put-instance_method) as such:
```ruby
def put(io, id, **options)
  options.merge!(content_md5: Digest::MD5.base64digest(File.read(io))) if 
    options[:content_type] == 'video/mp4'
  object(id).put(body: io, **options)
end
```

**Comment by janko-m** [comment] 2016-04-25 10:44
Thank you for tracking down the issue. That indeed is strange, that it only happens with one type of files. Maybe it depends on the filesize. The problem is that this reads the whole file in memory (on top of aws-sdk already doing it), so it wouldn't be ideal to add this workaround by default.

Is the error produced if you replace `Digest::MD5.base64digest(File.read(io))` with `Digest::MD5.base64digest(io.read); io.rewind`? I'm just trying to figure out how does aws-sdk get the bad MD5 hash. Does this happen with any video? Just so that I can easily obtain a file with which it errors, so that I can debug.

By the way, are you post-processing videos with a service like Zencoder, so that's why you're making a single version which contains the original file? If this is how you `#process` method looks like, you don't need to download & reupload, you can simply pass the IO object, and S3 storage will do a simple S3 COPY from `cache` to `store`.

```rb
  def process(io, context)
    case context[:phase]
    when :store
      { default: io }
    end
  end
```

That could be a workaround, although I would like to solve the issue with MD5 anyway.

**Comment by janko-m** [comment] 2016-04-25 11:42
Aha, I see that you probably did it for extracting metadata. The following should work for that:

```rb
  def process(io, context)
    case context[:phase]
    when :store
      metadata = extract_metadata(io.to_io)
      io.metadata.update(metadata)
      io.close
      { default: io }
    end
  end
```

The restore_cached_data plugin does something similar, but already when assigning the cached file, so it's in foreground, and it also calls `Shrine::UploadedFile#exists?` which does an additional HTTP request (this probably isn't necessary now when I think about it). It would probably be worthwhile to make a plugin for the above behaviour, maybe that's a generalized version of restore_cached_data.

**Comment by jaymanklu** [comment] 2016-04-26 14:40
Hi,

Thanks for the detailed information on probable causes.

Meanwhile, I have upgraded to latest release of shrine `v 1.4.2` and the issue seems to be not reproducible in `v 1.4.2` at the first glance. I will test it out extensively over next few days and update here on the observations.

**Comment by janko-m** [comment] 2016-05-03 07:52
Which version of Shrine were you using before, when the error was happening? Do you maybe have a video with which it was failing, or at least the approximate filesize? I tried with a simple 5MB .mp4 video and everything was fine, but maybe it should be larger.

But it seems to me that this must be a bug in aws-sdk gem and not Shrine, because of the nondeterministic nature of it.

**Comment by janko-m** [comment] 2016-05-07 18:16
I will close this as it is probably a bug in aws-sdk, feel free to reopen if the issue happens again and you can provide exact steps for reproducing.

**Closed by janko-m** 2016-05-07 18:16 UTC
